# Generated by Django 3.2 on 2024-09-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=255)),
                ('release_date', models.TextField()),
                ('running_time', models.TextField()),
                ('trailer_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movie_booking_api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.CharField(max_length=1)),
                ('number', models.PositiveIntegerField()),
                ('is_premium', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_booking_api.screening')),
            ],
        ),
        migrations.AddField(
            model_name='screening',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movie_booking_api.theatre'),
        ),
    ]
