# Generated by Django 3.2 on 2024-09-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking_api', '0002_auto_20240923_1341'),
        ('movie_booking_api', '0003_create_dummy_data'),
    ]

    operations = [
    ]
