# Generated by Django 3.2 on 2024-10-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_booking_api", "0004_auto_20240928_0831"),
    ]

    from movie_booking_api.generate import create_dummy_data

    operations = [migrations.RunPython(create_dummy_data)]
