# Generated by Django 3.2 on 2024-09-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_booking_api", "0006_merge_20240925_0522"),
    ]

    from movie_booking_api.generate import create_dummy_data

    operations = [
        migrations.RunPython(create_dummy_data),
    ]
